function criaWeather() {
    weather = createElement('div','');
    weather.style('backdrop-filter', 'blur(5px)');
    weather.class('panel');
    weather.style('box-shadow', '0px 5px 34px -15px rgba(0,0,0,0.55)');
    weather.style('background', 'rgba(255,255,255,0.24)');
    weather.style('max-width', "100%");
    weather.style('margin', '10px 15px');
    weather.style('padding-bottom', '5px');
    weather.style('color', '#ccc');
    weather.style('border-radius', '10px');
    weather.mouseClicked(mostraWeather);
    weatherImg = createDiv('');
    weatherImg.parent(weather);
    weatherImg.class('weather-content');
    weatherImg.style('max-width', '100%');
    weatherImg.style('height', '250px');
    weatherImg.style('background-position', 'center');
    weatherImg.style('background-size', 'cover');
    weatherImg.style('background-repeat', 'no-repeat');
    weatherImg.style('border-radius', '10px 10px 0px 0px');
    weatherImg.style('background-size', '100px 100px');
    weatherIcon = createImg('images/weatherIcon.png','');
    weatherIcon.parent(weather);
    weatherIcon.class('weather-content');
    weatherIcon.style('float', 'left');
    weatherIcon.style('width', '100px');
    weatherIcon.style('background-position', 'center');
    weatherIcon.style('background-repeat', 'no-repeat');
    weatherLabel = createElement('p', 'Clima');
    weatherLabel.style('font-weight', '500');
    weatherLabel.class('weather-content');
    weatherLabel.style('font-size', '1.5em');
    weatherLabel.style('padding', '0 15px');
    weatherLabel.style('margin', '0px 0px 0px 0px');
    weatherLabel.style('margin', '35px 0px 0px 0px');
    weatherLabel.style('width', '210px');
    weatherLabel.style('color', '#fff');
    weatherLabel.style('float', 'left');
    weatherLabel.parent(weather);
    weatherTemp = createElement('p','');
    weatherTemp.style('font-weight', '500');
    weatherTemp.style('text-align', 'center');
    weatherTemp.class('weather-content');
    weatherTemp.style('font-size', '3em');
    weatherTemp.style('margin', '0 15px');
    weatherTemp.style('color', '#fff');
    weatherTemp.parent(weather);
    weatherStatus = createElement('p','');
    weatherStatus.style('font-weight', '300');
    weatherStatus.style('text-align', 'center');
    weatherStatus.class('weather-content');
    weatherStatus.style('font-size', '1.5em');
    weatherStatus.style('margin', '0 15px');
    weatherStatus.parent(weather);
    weatherCity = createElement('p', '');
    weatherCity.style('padding', '0 15px');
    weatherCity.class('weather-content');
    weatherCity.style('font-weight', '300');
    weatherCity .style('text-align', 'center');
    weatherCity.parent(weather);
    weatherButton = createButton('VOLTAR');
    weatherButton.parent(weather);
    weatherButton.style('background-color', '#2E1974');
    weatherButton.style('color', '#fff');
    weatherButton.style('border', 'none');
    weatherButton.style('border-radius', '5px');
    weatherButton.style('padding', '10px');
    weatherButton.style('margin', '10px 10px');
    weatherButton.mousePressed(escondeWeather);
    weather.style('height', '100px');
    weather.style('overflow', 'hidden');
    weatherImg.hide();
    weatherTemp.hide();
    weatherCity.hide();
    weatherButton.hide();
    
}

function mostraWeather(){
  weatherTemp.html(weatherTempRes+'ºC');
  weatherCity.html(weatherCityRes);
  weatherStatus.html(weatherStatusRes);
  weatherImg.style('background-image', 'url(http://openweathermap.org/img/wn/'+weatherImgRes+'@2x.png)');
  weatherImg.style('height', '100px');
  weatherIcon.hide();
  weatherLabel.hide();
  weatherTemp.show();
  weatherImg.show();
  weatherStatus.show();
  weatherCity.show();
  weather.style('height', '');
  weather.style('width', '');
  weather.style('overflow', 'visible');
  weatherButton.style('width' ,weather.size().width-20+'px');
  weatherButton.show();
};

function escondeWeather(){
  weatherIcon.show();
  weatherLabel.show();
  weatherTemp.hide();
  weatherButton.hide();
  weatherImg.hide();
  weatherCity.hide();
  weatherStatus.hide();
  weather.style('height', '100px');
  weather.style('overflow', 'hidden');
};